from qiskit_ibm_runtime.fake_provider.backends import (
    FakeAlmadenV2,
    FakeArmonkV2,
    FakeAthensV2,
    FakeAuckland,
    FakeBelemV2,
    FakeBoeblingenV2,
    FakeBogotaV2,
    FakeBrooklynV2,
    FakeBurlingtonV2,
    FakeCairoV2,
    FakeCambridgeV2,
    FakeCasablancaV2,
    FakeEssexV2,
    FakeGeneva,
    FakeGuadalupeV2,
    FakeHanoiV2,
    FakeJakartaV2,
    FakeJohannesburgV2,
    FakeKolkataV2,
    FakeLagosV2,
    FakeLimaV2,
    FakeLondonV2,
    FakeManhattanV2,
    FakeManilaV2,
    FakeMelbourneV2,
    FakeMontrealV2,
    FakeMumbaiV2,
    FakeNairobiV2,
    FakeOslo,
    FakeOurenseV2,
    FakeParisV2,
    FakePerth,
    FakePrague,
    FakePoughkeepsieV2,
    FakeQuitoV2,
    FakeRochesterV2,
    FakeRomeV2,
    FakeSantiagoV2,
    FakeSherbrooke,
    FakeSingaporeV2,
    FakeSydneyV2,
    FakeTorontoV2,
    FakeValenciaV2,
    FakeVigoV2,
    FakeWashingtonV2,
    FakeYorktownV2,
)

# BackendV2, Backends
fake_backend_list = {
    "almaden": FakeAlmadenV2(),
    "armonk": FakeArmonkV2(),
    "athens": FakeAthensV2(),
    "auckland": FakeAuckland(),
    "belem": FakeBelemV2(),
    "boeblingen": FakeBoeblingenV2(),
    "bogota": FakeBogotaV2(),
    "brooklyn": FakeBrooklynV2(),
    "burlington": FakeBurlingtonV2(),
    "cairo": FakeCairoV2(),
    "cambridge": FakeCambridgeV2(),
    "casablanca": FakeCasablancaV2(),
    "essex": FakeEssexV2(),
    "geneva": FakeGeneva(),
    "guadalupe": FakeGuadalupeV2(),
    "hanoi": FakeHanoiV2(),
    "jakarta": FakeJakartaV2(),
    "johannesburg": FakeJohannesburgV2(),
    "kolkata": FakeKolkataV2(),
    "lagos": FakeLagosV2(),
    "lima": FakeLimaV2(),
    "london": FakeLondonV2(),
    "manhattan": FakeManhattanV2(),
    "manila": FakeManilaV2(),
    "melbourne": FakeMelbourneV2(),
    "montreal": FakeMontrealV2(),
    "mumbai": FakeMumbaiV2(),
    "nairobi": FakeNairobiV2(),
    "oslo": FakeOslo(),
    "ourense": FakeOurenseV2(),
    "paris": FakeParisV2(),
    "perth": FakePerth(),
    "prague": FakePrague(),
    "poughkeepsie": FakePoughkeepsieV2(),
    "quito": FakeQuitoV2(),
    "rochester": FakeRochesterV2(),
    "rome": FakeRomeV2(),
    "santiago": FakeSantiagoV2(),
    "sherbrooke": FakeSherbrooke(),
    "singapore": FakeSingaporeV2(),
    "sydney": FakeSydneyV2(),
    "toronto": FakeTorontoV2(),
    "valencia": FakeValenciaV2(),
    "vigo": FakeVigoV2(),
    "washington": FakeWashingtonV2(),
    "yorktown": FakeYorktownV2(),
}
