---
name: Docs Upload (executor)

on:
  push:
    branches: [ "executor_preview" ]

jobs:
  doc_publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.9.12'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -U virtualenv setuptools wheel tox
        sudo apt-get install -y graphviz pandoc
    - name: Build docs
      run: tox -e docs -- --tag executor
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: html_docs_executor
        path: docs/_build/html
    - name: Bypass Jekyll Processing # Necessary for setting the correct css path
      run: touch docs/_build/html/.nojekyll
    - name: Deploy
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        folder: docs/_build/html/
