# This code is part of Qiskit.
#
# (C) Copyright IBM 2023.
#
# This code is licensed under the Apache License, Version 2.0. You may
# obtain a copy of this license in the LICENSE.txt file in the root directory
# of this source tree or at http://www.apache.org/licenses/LICENSE-2.0.
#
# Any modifications or derivative works of this code must retain this
# copyright notice, and modified files need to carry a notice indicating
# that they have been altered from the originals.

name: Q-CTRL Tests
on:
  schedule:
    - cron: '0 1 * * *'
  push:
      tags:
        - "*"
  workflow_dispatch:
jobs:
  integration-tests:
    name: Run integration tests - ${{ matrix.environment }}
    runs-on: ${{ matrix.os }}
    strategy:
      # avoid cancellation of in-progress jobs if any matrix job fails
      fail-fast: false
      matrix:
        python-version: [ 3.9 ]
        os: [ "ubuntu-latest" ]
        environment: [ "ibm-cloud-staging" ]
    environment: ${{ matrix.environment }}
    env:
      QISKIT_IBM_TOKEN: ${{ secrets.QISKIT_IBM_TOKEN_QCTRL }}
      QISKIT_IBM_URL: ${{ secrets.QISKIT_IBM_URL }}
      QISKIT_IBM_INSTANCE: ${{ secrets.QISKIT_IBM_INSTANCE_QCTRL }}
      CHANNEL_STRATEGY: q-ctrl
      LOG_LEVEL: DEBUG
      STREAM_LOG: True
      QISKIT_IN_PARALLEL: True
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -c constraints.txt -r requirements-dev.txt -e .
      - name: Run q-ctrl tests
        run: python -m unittest test/qctrl/test_qctrl.py
